version: "3"

services:
  discovery-service:
    image: rhw/discovery-service:1.0
    ports:
      - 8761:8761
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - ecommerce-network
    restart: always
networks:
  ecommerce-network:
    external:
      name: ecommerce-network