server:
  port: 0 # ?? ??
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  h2:
    console:
      enabled: true # console ??
      settings:
        web-allow-others: true # ?? ?? ??
      path: /h2-console
eureka:
  instance:
    instance-id: user-service
    hostname: user-service
  client:
    register-with-eureka: true # ????
    fetch-registry: true # ??? ??? ???? ??? ????? ????.
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
greeting:
  message: Welcome to the Simple E-commerce.

logging:
  level:
    com.example.userservice.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus # ???? ??