version: "3"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/volume:/prometheus
    networks:
      - ecommerce-network
    restart: always
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./grafana/volume:/var/lib/grafana
    networks:
      - ecommerce-network
    restart: always
networks:
  ecommerce-network:
    external:
      name: ecommerce-network